// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23Y586xScMbuCMWJa-WnjENqQRx5IFp0',
    appId: '1:154822156701:web:9ed17373fba67072b7cf74',
    messagingSenderId: '154822156701',
    projectId: 'fir-actatest',
    authDomain: 'fir-actatest.firebaseapp.com',
    storageBucket: 'fir-actatest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQSW2r2-Mw_orVavhJiudMyZNpX0ZGqw',
    appId: '1:154822156701:android:e374de6f16604ad9b7cf74',
    messagingSenderId: '154822156701',
    projectId: 'fir-actatest',
    storageBucket: 'fir-actatest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfh_JLQb2t7khCIoLzltEW2i3Kjvy4osc',
    appId: '1:154822156701:ios:ad90e5321a3dc7f9b7cf74',
    messagingSenderId: '154822156701',
    projectId: 'fir-actatest',
    storageBucket: 'fir-actatest.firebasestorage.app',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfh_JLQb2t7khCIoLzltEW2i3Kjvy4osc',
    appId: '1:154822156701:ios:ad90e5321a3dc7f9b7cf74',
    messagingSenderId: '154822156701',
    projectId: 'fir-actatest',
    storageBucket: 'fir-actatest.firebasestorage.app',
    iosBundleId: 'com.example.flutterBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB23Y586xScMbuCMWJa-WnjENqQRx5IFp0',
    appId: '1:154822156701:web:abfc31ff93695353b7cf74',
    messagingSenderId: '154822156701',
    projectId: 'fir-actatest',
    authDomain: 'fir-actatest.firebaseapp.com',
    storageBucket: 'fir-actatest.firebasestorage.app',
  );
}
